<?php
/**
 * Magecom
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magecom.net so we can send you a copy immediately.
 *
 * @category Magecom
 * @package Magecom_Module
 * @copyright Copyright (c) 2017 Magecom, Inc. (http://www.magecom.net)
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Tasks\Brand\Controller\Products;

use Magento\Catalog\Api\CategoryRepositoryInterface;
use Magento\Catalog\Model\Layer\Resolver;
use Magento\Framework\App\Action\Context;
use Magento\Framework\View\Result\PageFactory;
use Magento\Framework\Exception\NoSuchEntityException;

/**
 * Class Index
 * @package Tasks\Brand\Controller\Products
 */
class Index extends \Magento\Catalog\Controller\Category\View
{
    /**
     * @var \Tasks\Brand\Helper\Data
     */
    protected $_brandConfig;

    /**
     * @var \Tasks\Brand\Model\ResourceModel\Brand\CollectionFactory
     */
    protected $_brandCollection;

    /**
     * Index constructor.
     * @param Context $context
     * @param \Magento\Catalog\Model\Design $catalogDesign
     * @param \Magento\Catalog\Model\Session $catalogSession
     * @param \Magento\Framework\Registry $coreRegistry
     * @param \Magento\Store\Model\StoreManagerInterface $storeManager
     * @param \Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator $categoryUrlPathGenerator
     * @param PageFactory $resultPageFactory
     * @param \Magento\Framework\Controller\Result\ForwardFactory $resultForwardFactory
     * @param Resolver $layerResolver
     * @param CategoryRepositoryInterface $categoryRepository
     * @param \Tasks\Brand\Model\ResourceModel\Brand\Collection $_brandCollection
     * @param \Tasks\Brand\Helper\Data $brandConfig
     */
    public function __construct(
        \Magento\Framework\App\Action\Context $context,
        \Magento\Catalog\Model\Design $catalogDesign,
        \Magento\Catalog\Model\Session $catalogSession,
        \Magento\Framework\Registry $coreRegistry,
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        \Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator $categoryUrlPathGenerator,
        PageFactory $resultPageFactory,
        \Magento\Framework\Controller\Result\ForwardFactory $resultForwardFactory,
        Resolver $layerResolver,
        CategoryRepositoryInterface $categoryRepository,
        \Tasks\Brand\Model\ResourceModel\Brand\Collection $_brandCollection,
        \Tasks\Brand\Helper\Data $brandConfig
    ) {
        $this->_brandCollection = $_brandCollection;
        $this->_brandConfig = $brandConfig;
        parent::__construct($context, $catalogDesign, $catalogSession, $coreRegistry, $storeManager, $categoryUrlPathGenerator, $resultPageFactory, $resultForwardFactory, $layerResolver, $categoryRepository);
    }

    /**
     * @return bool|\Magento\Catalog\Api\Data\CategoryInterface
     */
    protected function _initCategory()
    {
        try {
            $category = $this->categoryRepository->get(1, $this->_storeManager->getStore()->getId());
        } catch (NoSuchEntityException $e) {
            return false;
        }

        $this->_catalogSession->setLastVisitedCategoryId($category->getId());
        $this->_coreRegistry->register('current_category', $category);
        try {
            $this->_eventManager->dispatch(
                'catalog_controller_category_init_after',
                ['category' => $category, 'controller_action' => $this]
            );
        } catch (\Magento\Framework\Exception\LocalizedException $e) {
            $this->_objectManager->get('Psr\Log\LoggerInterface')->critical($e);
            return false;
        }

        return $category;
    }

    /**
     * @return \Magento\Framework\Controller\ResultInterface
     */
    public function execute()
    {
        $page = parent::execute(); // TODO: Change the autogenerated stub
        $brandId = $this->_request->getParam('brand');
        $brand =
            $this->
            _brandCollection
                ->addAttributeToSelect('name')
                ->addAttributeToSelect('meta_title')
                ->addAttributeToSelect('meta_description')
                ->addAttributeToSelect('meta_keywords')
                ->addFieldToFilter('entity_id', ['eq' => $brandId])
                ->getFirstItem();

        $meta_title = $brand->getData('meta_title')? $brand->getData('meta_title')
            :$this->_brandConfig->getGeneralConfig('meta_title');

        $meta_description = $brand->getData('meta_description')? $brand->getData('meta_description')
            :$this->_brandConfig->getGeneralConfig('meta_description');

        $meta_keywords = $brand->getData('meta_keywords')? $brand->getData('meta_keywords')
            :$this->_brandConfig->getGeneralConfig('meta_keywords');

        $page->getConfig()->getTitle()->set($meta_title);
        $page->getConfig()->setDescription($meta_description);
        $page->getConfig()->setKeywords($meta_keywords);
        $this->_view->getLayout()->getBlock('page.main.title')->setPageTitle($brand->getName());
        return $page;

    }

}